export enum RoutePath {
  HOMEPAGE = "/",
  TESTE = "/teste",
  AUTHLOGIN = "/login",
  CREATEUSER = "/novousuarrio",
  USERFORGOTPASSWORD = "/esqueciminhasenha",
  MYACCOUNT = "/minhaconta",
  LOGOUT = "/logout",
  FILTERBYMONEY = "/maisricos",
  MYBINGO = "/bingo",
  RESETSECTION = "/resetarjogo",
  SOCKET = "/socket",
  VICTORYMODAL = "/vitoria",
  DEFEAT = "/defeat",
}
